print("first line")
print("sec line")
print("third line")
print("fourth line")
print("fifth line created by dev1")
print("six line by dev 1")
print("seventh line by dev1")
print("eight line by master")
print("nineth line written by dev1)
print("hi i am check this on git kraken")
print("written by master")
print("hii")